### ISSUE TITLE
navigation bar inhoud moet hidden

### ISSUE THREAD

**Issue by aliceafanasieva** [christoph3r3w/the-startup-responsive-interactieve-website#11]
De content van navigation bar moet worden verborgen en dat werkt nog niet in de code.

[https://github.com/christoph3r3w/the-startup-responsive-interactieve-website/blob/22f687fb4af4af3a9ba93d0d698ff9c9dfe0e513/B-corp/style.css#L101C1-L104C2](url)

**Comment by christoph3r3w** [comment]
the issue was that my CSS file did not update when the new version was uploaded
