### ISSUE TITLE
add padding 

### ISSUE THREAD

**Issue by aliceafanasieva** [christoph3r3w/the-startup-responsive-interactieve-website#12]
Add padding bij main content teksten.
<img width="451" alt="image" src="https://github.com/christoph3r3w/the-startup-responsive-interactieve-website/assets/66431299/5343cb6c-a04b-4117-8bc7-05b2d1192abc">

**Comment by christoph3r3w** [comment]
thanks for the feedback. it was bug in the code and it will be fixed
